# Generated by Django 4.0.4 on 2022-05-14 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_alter_bookings_reserve_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='reserve_time_end',
            field=models.TimeField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookings',
            name='reserve_time_start',
            field=models.TimeField(default=None),
            preserve_default=False,
        ),
    ]
