# Generated by Django 4.0.4 on 2022-05-14 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_bookings_reserve_time_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='reserve_time_end',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='reserve_time_start',
            field=models.TimeField(null=True),
        ),
    ]
