# Generated by Django 4.0.4 on 2022-05-15 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_alter_bookings_reserve_time_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='email',
            field=models.EmailField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookings',
            name='phone',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookings',
            name='reserverFname',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookings',
            name='reserverLname',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookings',
            name='specialRequest',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
