# Generated by Django 4.0.4 on 2022-05-15 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_bookings_email_bookings_phone_bookings_reserverfname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='phone',
            field=models.CharField(max_length=50),
        ),
    ]
