# Generated by Django 4.0.4 on 2022-06-08 09:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_remove_orders_items_orders_complete_orders_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurants',
            name='owner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
