# Generated by Django 4.0.4 on 2022-06-08 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_restaurants_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurants',
            old_name='photos',
            new_name='photo',
        ),
        migrations.AddField(
            model_name='items',
            name='image',
            field=models.ImageField(default=None, upload_to=''),
            preserve_default=False,
        ),
    ]
